version: "3.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  slim-php:
    build: .
    command: /bin/sh /var/run/start-services.sh
    volumes:
      - ./app:/www
    ports:
      - "8080:80"
    depends_on:
      - db